/*
 * BaSyx AAS Environment Component
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mateusmolina.basyx.aasenvironment.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.mateusmolina.basyx.aasenvironment.client.model.EmbeddedDataSpecification;
import com.github.mateusmolina.basyx.aasenvironment.client.model.Reference;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AdministrativeInformation
 */
public class AdministrativeInformationTest {
    private final AdministrativeInformation model = new AdministrativeInformation();

    /**
     * Model tests for AdministrativeInformation
     */
    @Test
    public void testAdministrativeInformation() {
        // TODO: test AdministrativeInformation
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'creator'
     */
    @Test
    public void creatorTest() {
        // TODO: test creator
    }

    /**
     * Test the property 'revision'
     */
    @Test
    public void revisionTest() {
        // TODO: test revision
    }

    /**
     * Test the property 'templateID'
     */
    @Test
    public void templateIDTest() {
        // TODO: test templateID
    }

    /**
     * Test the property 'embeddedDataSpecifications'
     */
    @Test
    public void embeddedDataSpecificationsTest() {
        // TODO: test embeddedDataSpecifications
    }

}
