/*
 * BaSyx AAS Environment Component
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mateusmolina.basyx.aasenvironment.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.mateusmolina.basyx.aasenvironment.client.model.Resource;
import com.github.mateusmolina.basyx.aasenvironment.client.model.SpecificAssetID;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AssetInformation
 */
public class AssetInformationTest {
    private final AssetInformation model = new AssetInformation();

    /**
     * Model tests for AssetInformation
     */
    @Test
    public void testAssetInformation() {
        // TODO: test AssetInformation
    }

    /**
     * Test the property 'assetKind'
     */
    @Test
    public void assetKindTest() {
        // TODO: test assetKind
    }

    /**
     * Test the property 'assetType'
     */
    @Test
    public void assetTypeTest() {
        // TODO: test assetType
    }

    /**
     * Test the property 'defaultThumbnail'
     */
    @Test
    public void defaultThumbnailTest() {
        // TODO: test defaultThumbnail
    }

    /**
     * Test the property 'globalAssetID'
     */
    @Test
    public void globalAssetIDTest() {
        // TODO: test globalAssetID
    }

    /**
     * Test the property 'specificAssetIds'
     */
    @Test
    public void specificAssetIdsTest() {
        // TODO: test specificAssetIds
    }

}
