/*
 * BaSyx AAS Environment Component
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mateusmolina.basyx.aasenvironment.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.mateusmolina.basyx.aasenvironment.client.model.AdministrativeInformation;
import com.github.mateusmolina.basyx.aasenvironment.client.model.AssetInformation;
import com.github.mateusmolina.basyx.aasenvironment.client.model.EmbeddedDataSpecification;
import com.github.mateusmolina.basyx.aasenvironment.client.model.Extension;
import com.github.mateusmolina.basyx.aasenvironment.client.model.LangStringNameType;
import com.github.mateusmolina.basyx.aasenvironment.client.model.LangStringTextType;
import com.github.mateusmolina.basyx.aasenvironment.client.model.Reference;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AssetAdministrationShell
 */
public class AssetAdministrationShellTest {
    private final AssetAdministrationShell model = new AssetAdministrationShell();

    /**
     * Model tests for AssetAdministrationShell
     */
    @Test
    public void testAssetAdministrationShell() {
        // TODO: test AssetAdministrationShell
    }

    /**
     * Test the property 'assetInformation'
     */
    @Test
    public void assetInformationTest() {
        // TODO: test assetInformation
    }

    /**
     * Test the property 'submodels'
     */
    @Test
    public void submodelsTest() {
        // TODO: test submodels
    }

    /**
     * Test the property 'derivedFrom'
     */
    @Test
    public void derivedFromTest() {
        // TODO: test derivedFrom
    }

    /**
     * Test the property 'embeddedDataSpecifications'
     */
    @Test
    public void embeddedDataSpecificationsTest() {
        // TODO: test embeddedDataSpecifications
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'administration'
     */
    @Test
    public void administrationTest() {
        // TODO: test administration
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'idShort'
     */
    @Test
    public void idShortTest() {
        // TODO: test idShort
    }

    /**
     * Test the property 'extensions'
     */
    @Test
    public void extensionsTest() {
        // TODO: test extensions
    }

}
