/*
 * BaSyx AAS Environment Component
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mateusmolina.basyx.aasenvironment.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.mateusmolina.basyx.aasenvironment.client.model.Reference;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmbeddedDataSpecification
 */
public class EmbeddedDataSpecificationTest {
    private final EmbeddedDataSpecification model = new EmbeddedDataSpecification();

    /**
     * Model tests for EmbeddedDataSpecification
     */
    @Test
    public void testEmbeddedDataSpecification() {
        // TODO: test EmbeddedDataSpecification
    }

    /**
     * Test the property 'dataSpecification'
     */
    @Test
    public void dataSpecificationTest() {
        // TODO: test dataSpecification
    }

    /**
     * Test the property 'dataSpecificationContent'
     */
    @Test
    public void dataSpecificationContentTest() {
        // TODO: test dataSpecificationContent
    }

}
