/*
 * BaSyx AAS Environment Component
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mateusmolina.basyx.aasenvironment.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.mateusmolina.basyx.aasenvironment.client.model.OperationVariable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OperationRequest
 */
public class OperationRequestTest {
    private final OperationRequest model = new OperationRequest();

    /**
     * Model tests for OperationRequest
     */
    @Test
    public void testOperationRequest() {
        // TODO: test OperationRequest
    }

    /**
     * Test the property 'inoutputArguments'
     */
    @Test
    public void inoutputArgumentsTest() {
        // TODO: test inoutputArguments
    }

    /**
     * Test the property 'inputArguments'
     */
    @Test
    public void inputArgumentsTest() {
        // TODO: test inputArguments
    }

    /**
     * Test the property 'clientTimeoutDuration'
     */
    @Test
    public void clientTimeoutDurationTest() {
        // TODO: test clientTimeoutDuration
    }

}
