/*
 * BaSyx AAS Environment Component
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mateusmolina.basyx.aasenvironment.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.mateusmolina.basyx.aasenvironment.client.model.Reference;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SpecificAssetID
 */
public class SpecificAssetIDTest {
    private final SpecificAssetID model = new SpecificAssetID();

    /**
     * Model tests for SpecificAssetID
     */
    @Test
    public void testSpecificAssetID() {
        // TODO: test SpecificAssetID
    }

    /**
     * Test the property 'externalSubjectID'
     */
    @Test
    public void externalSubjectIDTest() {
        // TODO: test externalSubjectID
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'semanticID'
     */
    @Test
    public void semanticIDTest() {
        // TODO: test semanticID
    }

    /**
     * Test the property 'supplementalSemanticIds'
     */
    @Test
    public void supplementalSemanticIdsTest() {
        // TODO: test supplementalSemanticIds
    }

}
