/*
 * BaSyx AAS Environment Component
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mateusmolina.basyx.aasenvironment.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.mateusmolina.basyx.aasenvironment.client.model.OperationVariable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.github.mateusmolina.basyx.aasenvironment.client.invoker.JSON;


/**
 * Operation request object
 */
@JsonPropertyOrder({
  OperationRequest.JSON_PROPERTY_INOUTPUT_ARGUMENTS,
  OperationRequest.JSON_PROPERTY_INPUT_ARGUMENTS,
  OperationRequest.JSON_PROPERTY_CLIENT_TIMEOUT_DURATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-03T13:20:12.648099800+02:00[Europe/Berlin]")
public class OperationRequest {
  public static final String JSON_PROPERTY_INOUTPUT_ARGUMENTS = "inoutputArguments";
  private List<OperationVariable> inoutputArguments;

  public static final String JSON_PROPERTY_INPUT_ARGUMENTS = "inputArguments";
  private List<OperationVariable> inputArguments;

  public static final String JSON_PROPERTY_CLIENT_TIMEOUT_DURATION = "clientTimeoutDuration";
  private String clientTimeoutDuration;

  public OperationRequest() { 
  }

  public OperationRequest inoutputArguments(List<OperationVariable> inoutputArguments) {
    this.inoutputArguments = inoutputArguments;
    return this;
  }

  public OperationRequest addInoutputArgumentsItem(OperationVariable inoutputArgumentsItem) {
    if (this.inoutputArguments == null) {
      this.inoutputArguments = new ArrayList<>();
    }
    this.inoutputArguments.add(inoutputArgumentsItem);
    return this;
  }

   /**
   * Get inoutputArguments
   * @return inoutputArguments
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INOUTPUT_ARGUMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<OperationVariable> getInoutputArguments() {
    return inoutputArguments;
  }


  @JsonProperty(JSON_PROPERTY_INOUTPUT_ARGUMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInoutputArguments(List<OperationVariable> inoutputArguments) {
    this.inoutputArguments = inoutputArguments;
  }


  public OperationRequest inputArguments(List<OperationVariable> inputArguments) {
    this.inputArguments = inputArguments;
    return this;
  }

  public OperationRequest addInputArgumentsItem(OperationVariable inputArgumentsItem) {
    if (this.inputArguments == null) {
      this.inputArguments = new ArrayList<>();
    }
    this.inputArguments.add(inputArgumentsItem);
    return this;
  }

   /**
   * Get inputArguments
   * @return inputArguments
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_ARGUMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<OperationVariable> getInputArguments() {
    return inputArguments;
  }


  @JsonProperty(JSON_PROPERTY_INPUT_ARGUMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputArguments(List<OperationVariable> inputArguments) {
    this.inputArguments = inputArguments;
  }


  public OperationRequest clientTimeoutDuration(String clientTimeoutDuration) {
    this.clientTimeoutDuration = clientTimeoutDuration;
    return this;
  }

   /**
   * Get clientTimeoutDuration
   * @return clientTimeoutDuration
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIENT_TIMEOUT_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientTimeoutDuration() {
    return clientTimeoutDuration;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_TIMEOUT_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientTimeoutDuration(String clientTimeoutDuration) {
    this.clientTimeoutDuration = clientTimeoutDuration;
  }


  /**
   * Return true if this OperationRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationRequest operationRequest = (OperationRequest) o;
    return Objects.equals(this.inoutputArguments, operationRequest.inoutputArguments) &&
        Objects.equals(this.inputArguments, operationRequest.inputArguments) &&
        Objects.equals(this.clientTimeoutDuration, operationRequest.clientTimeoutDuration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inoutputArguments, inputArguments, clientTimeoutDuration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationRequest {\n");
    sb.append("    inoutputArguments: ").append(toIndentedString(inoutputArguments)).append("\n");
    sb.append("    inputArguments: ").append(toIndentedString(inputArguments)).append("\n");
    sb.append("    clientTimeoutDuration: ").append(toIndentedString(clientTimeoutDuration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

