/*
 * BaSyx AAS Environment Component
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mateusmolina.basyx.aasenvironment.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.mateusmolina.basyx.aasenvironment.client.model.Reference;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.github.mateusmolina.basyx.aasenvironment.client.invoker.JSON;


/**
 * Qualifier
 */
@JsonPropertyOrder({
  Qualifier.JSON_PROPERTY_TYPE,
  Qualifier.JSON_PROPERTY_KIND,
  Qualifier.JSON_PROPERTY_VALUE_TYPE,
  Qualifier.JSON_PROPERTY_VALUE_I_D,
  Qualifier.JSON_PROPERTY_VALUE,
  Qualifier.JSON_PROPERTY_SEMANTIC_I_D,
  Qualifier.JSON_PROPERTY_SUPPLEMENTAL_SEMANTIC_IDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-03T13:20:12.648099800+02:00[Europe/Berlin]")
public class Qualifier {
  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  /**
   * Gets or Sets kind
   */
  public enum KindEnum {
    CONCEPT_QUALIFIER("CONCEPT_QUALIFIER"),
    
    TEMPLATE_QUALIFIER("TEMPLATE_QUALIFIER"),
    
    VALUE_QUALIFIER("VALUE_QUALIFIER");

    private String value;

    KindEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static KindEnum fromValue(String value) {
      for (KindEnum b : KindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_KIND = "kind";
  private KindEnum kind;

  /**
   * Gets or Sets valueType
   */
  public enum ValueTypeEnum {
    ANY_URI("ANY_URI"),
    
    BASE64BINARY("BASE64BINARY"),
    
    BOOLEAN("BOOLEAN"),
    
    BYTE("BYTE"),
    
    DATE("DATE"),
    
    DATE_TIME("DATE_TIME"),
    
    DECIMAL("DECIMAL"),
    
    DOUBLE("DOUBLE"),
    
    DURATION("DURATION"),
    
    FLOAT("FLOAT"),
    
    GDAY("GDAY"),
    
    GMONTH("GMONTH"),
    
    GMONTH_DAY("GMONTH_DAY"),
    
    GYEAR("GYEAR"),
    
    GYEAR_MONTH("GYEAR_MONTH"),
    
    HEX_BINARY("HEX_BINARY"),
    
    INT("INT"),
    
    INTEGER("INTEGER"),
    
    LONG("LONG"),
    
    NEGATIVE_INTEGER("NEGATIVE_INTEGER"),
    
    NON_NEGATIVE_INTEGER("NON_NEGATIVE_INTEGER"),
    
    NON_POSITIVE_INTEGER("NON_POSITIVE_INTEGER"),
    
    POSITIVE_INTEGER("POSITIVE_INTEGER"),
    
    SHORT("SHORT"),
    
    STRING("STRING"),
    
    TIME("TIME"),
    
    UNSIGNED_BYTE("UNSIGNED_BYTE"),
    
    UNSIGNED_INT("UNSIGNED_INT"),
    
    UNSIGNED_LONG("UNSIGNED_LONG"),
    
    UNSIGNED_SHORT("UNSIGNED_SHORT");

    private String value;

    ValueTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ValueTypeEnum fromValue(String value) {
      for (ValueTypeEnum b : ValueTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VALUE_TYPE = "valueType";
  private ValueTypeEnum valueType;

  public static final String JSON_PROPERTY_VALUE_I_D = "valueID";
  private Reference valueID;

  public static final String JSON_PROPERTY_VALUE = "value";
  private String value;

  public static final String JSON_PROPERTY_SEMANTIC_I_D = "semanticID";
  private Reference semanticID;

  public static final String JSON_PROPERTY_SUPPLEMENTAL_SEMANTIC_IDS = "supplementalSemanticIds";
  private List<Reference> supplementalSemanticIds;

  public Qualifier() { 
  }

  public Qualifier type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public Qualifier kind(KindEnum kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public KindEnum getKind() {
    return kind;
  }


  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKind(KindEnum kind) {
    this.kind = kind;
  }


  public Qualifier valueType(ValueTypeEnum valueType) {
    this.valueType = valueType;
    return this;
  }

   /**
   * Get valueType
   * @return valueType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ValueTypeEnum getValueType() {
    return valueType;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueType(ValueTypeEnum valueType) {
    this.valueType = valueType;
  }


  public Qualifier valueID(Reference valueID) {
    this.valueID = valueID;
    return this;
  }

   /**
   * Get valueID
   * @return valueID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Reference getValueID() {
    return valueID;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueID(Reference valueID) {
    this.valueID = valueID;
  }


  public Qualifier value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(String value) {
    this.value = value;
  }


  public Qualifier semanticID(Reference semanticID) {
    this.semanticID = semanticID;
    return this;
  }

   /**
   * Get semanticID
   * @return semanticID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEMANTIC_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Reference getSemanticID() {
    return semanticID;
  }


  @JsonProperty(JSON_PROPERTY_SEMANTIC_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSemanticID(Reference semanticID) {
    this.semanticID = semanticID;
  }


  public Qualifier supplementalSemanticIds(List<Reference> supplementalSemanticIds) {
    this.supplementalSemanticIds = supplementalSemanticIds;
    return this;
  }

  public Qualifier addSupplementalSemanticIdsItem(Reference supplementalSemanticIdsItem) {
    if (this.supplementalSemanticIds == null) {
      this.supplementalSemanticIds = new ArrayList<>();
    }
    this.supplementalSemanticIds.add(supplementalSemanticIdsItem);
    return this;
  }

   /**
   * Get supplementalSemanticIds
   * @return supplementalSemanticIds
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPLEMENTAL_SEMANTIC_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Reference> getSupplementalSemanticIds() {
    return supplementalSemanticIds;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLEMENTAL_SEMANTIC_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupplementalSemanticIds(List<Reference> supplementalSemanticIds) {
    this.supplementalSemanticIds = supplementalSemanticIds;
  }


  /**
   * Return true if this Qualifier object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Qualifier qualifier = (Qualifier) o;
    return Objects.equals(this.type, qualifier.type) &&
        Objects.equals(this.kind, qualifier.kind) &&
        Objects.equals(this.valueType, qualifier.valueType) &&
        Objects.equals(this.valueID, qualifier.valueID) &&
        Objects.equals(this.value, qualifier.value) &&
        Objects.equals(this.semanticID, qualifier.semanticID) &&
        Objects.equals(this.supplementalSemanticIds, qualifier.supplementalSemanticIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, kind, valueType, valueID, value, semanticID, supplementalSemanticIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Qualifier {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    valueType: ").append(toIndentedString(valueType)).append("\n");
    sb.append("    valueID: ").append(toIndentedString(valueID)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    semanticID: ").append(toIndentedString(semanticID)).append("\n");
    sb.append("    supplementalSemanticIds: ").append(toIndentedString(supplementalSemanticIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

