/*
 * BaSyx AAS Environment Component
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mateusmolina.basyx.aasenvironment.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.mateusmolina.basyx.aasenvironment.client.model.Reference;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.github.mateusmolina.basyx.aasenvironment.client.invoker.JSON;


/**
 * SpecificAssetID
 */
@JsonPropertyOrder({
  SpecificAssetID.JSON_PROPERTY_EXTERNAL_SUBJECT_I_D,
  SpecificAssetID.JSON_PROPERTY_NAME,
  SpecificAssetID.JSON_PROPERTY_VALUE,
  SpecificAssetID.JSON_PROPERTY_SEMANTIC_I_D,
  SpecificAssetID.JSON_PROPERTY_SUPPLEMENTAL_SEMANTIC_IDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-03T13:20:12.648099800+02:00[Europe/Berlin]")
public class SpecificAssetID {
  public static final String JSON_PROPERTY_EXTERNAL_SUBJECT_I_D = "externalSubjectID";
  private Reference externalSubjectID;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_VALUE = "value";
  private String value;

  public static final String JSON_PROPERTY_SEMANTIC_I_D = "semanticID";
  private Reference semanticID;

  public static final String JSON_PROPERTY_SUPPLEMENTAL_SEMANTIC_IDS = "supplementalSemanticIds";
  private List<Reference> supplementalSemanticIds;

  public SpecificAssetID() { 
  }

  public SpecificAssetID externalSubjectID(Reference externalSubjectID) {
    this.externalSubjectID = externalSubjectID;
    return this;
  }

   /**
   * Get externalSubjectID
   * @return externalSubjectID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTERNAL_SUBJECT_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Reference getExternalSubjectID() {
    return externalSubjectID;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_SUBJECT_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalSubjectID(Reference externalSubjectID) {
    this.externalSubjectID = externalSubjectID;
  }


  public SpecificAssetID name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public SpecificAssetID value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(String value) {
    this.value = value;
  }


  public SpecificAssetID semanticID(Reference semanticID) {
    this.semanticID = semanticID;
    return this;
  }

   /**
   * Get semanticID
   * @return semanticID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEMANTIC_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Reference getSemanticID() {
    return semanticID;
  }


  @JsonProperty(JSON_PROPERTY_SEMANTIC_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSemanticID(Reference semanticID) {
    this.semanticID = semanticID;
  }


  public SpecificAssetID supplementalSemanticIds(List<Reference> supplementalSemanticIds) {
    this.supplementalSemanticIds = supplementalSemanticIds;
    return this;
  }

  public SpecificAssetID addSupplementalSemanticIdsItem(Reference supplementalSemanticIdsItem) {
    if (this.supplementalSemanticIds == null) {
      this.supplementalSemanticIds = new ArrayList<>();
    }
    this.supplementalSemanticIds.add(supplementalSemanticIdsItem);
    return this;
  }

   /**
   * Get supplementalSemanticIds
   * @return supplementalSemanticIds
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPLEMENTAL_SEMANTIC_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Reference> getSupplementalSemanticIds() {
    return supplementalSemanticIds;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLEMENTAL_SEMANTIC_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupplementalSemanticIds(List<Reference> supplementalSemanticIds) {
    this.supplementalSemanticIds = supplementalSemanticIds;
  }


  /**
   * Return true if this SpecificAssetID object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpecificAssetID specificAssetID = (SpecificAssetID) o;
    return Objects.equals(this.externalSubjectID, specificAssetID.externalSubjectID) &&
        Objects.equals(this.name, specificAssetID.name) &&
        Objects.equals(this.value, specificAssetID.value) &&
        Objects.equals(this.semanticID, specificAssetID.semanticID) &&
        Objects.equals(this.supplementalSemanticIds, specificAssetID.supplementalSemanticIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalSubjectID, name, value, semanticID, supplementalSemanticIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpecificAssetID {\n");
    sb.append("    externalSubjectID: ").append(toIndentedString(externalSubjectID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    semanticID: ").append(toIndentedString(semanticID)).append("\n");
    sb.append("    supplementalSemanticIds: ").append(toIndentedString(supplementalSemanticIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

