/*
 * BaSyx AAS Environment Component
 * AAS Environment API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: basyx-dev@eclipse.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mateusmolina.basyx.aasenvironment.client.api;

import com.github.mateusmolina.basyx.aasenvironment.client.invoker.*;
import com.github.mateusmolina.basyx.aasenvironment.client.invoker.auth.*;
import com.github.mateusmolina.basyx.aasenvironment.client.model.ConceptDescription;
import com.github.mateusmolina.basyx.aasenvironment.client.model.Result;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConceptDescriptionRepositoryApiApi
 */
public class ConceptDescriptionRepositoryApiApiTest {

    private final ConceptDescriptionRepositoryApiApi api = new ConceptDescriptionRepositoryApiApi();

    /**
     * Deletes a Concept Description
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteConceptDescriptionByIdTest() throws ApiException {
        //String cdIdentifier = null;
        //Result response = api.deleteConceptDescriptionById(cdIdentifier);
        // TODO: test validations
    }

    /**
     * Returns all Concept Descriptions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllConceptDescriptionsTest() throws ApiException {
        //String idShort = null;
        //String isCaseOf = null;
        //String dataSpecificationRef = null;
        //String limit = null;
        //String cursor = null;
        //String response = api.getAllConceptDescriptions(idShort, isCaseOf, dataSpecificationRef, limit, cursor);
        // TODO: test validations
    }

    /**
     * Returns a specific Concept Description
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConceptDescriptionByIdTest() throws ApiException {
        //String cdIdentifier = null;
        //Result response = api.getConceptDescriptionById(cdIdentifier);
        // TODO: test validations
    }

    /**
     * Creates a new Concept Description
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postConceptDescriptionTest() throws ApiException {
        //ConceptDescription conceptDescription = null;
        //Result response = api.postConceptDescription(conceptDescription);
        // TODO: test validations
    }

    /**
     * Updates an existing Concept Description
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putConceptDescriptionByIdTest() throws ApiException {
        //String cdIdentifier = null;
        //ConceptDescription conceptDescription = null;
        //Result response = api.putConceptDescriptionById(cdIdentifier, conceptDescription);
        // TODO: test validations
    }

}
